### ISSUE TITLE
Implement a mechanism for Redis cache flushing 

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1138]
**User Story:**
As an admin,
I sometimes need to update the database directly.
This can lead to inconsistencies with Redis cached entries.
Therefore, I need a way to manually flush the Redis cache to ensure data consistency.

**Problem:**
Currently, there is no direct method to purge the Redis cache from the AWS console. Flushing the cache must be done via the Redis console or AWS Systems Manager (SSM).

**Objective:**
Investigate available options and implement a repeatable, easy-to-use method for manually purging the Redis cache when necessary. Document the process.

**Tasks:**
- [x] Research methods to clear the Redis cache using AWS tools (e.g., Redis CLI, AWS SSM).
- [x] Implement a Python script or alternative solution to automate the cache purging process.
- [x] Test in local and staging
- [x] Document the solution, with step-by-step instructions for usage.
- [x] Deploy to master and confirm operation is as expected

**Comment by sadatmalik** [comment]
Opting to implement as a system admin API call for cleaner security access. Longer term it is better to introduce the Amazon service manager to manage cloud services.

From the TC admin api:

<img width="1116" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM200QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf38eb1f0b6b6a9f5809ec6a32a17a238046bffa/Screenshot%202024-07-05%20at%2013.18.48.png" alt="Screenshot 2024-07-05 at 13.18.48.png" />

Before and after in Redis:

<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3E0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b87bc4da8015654a36e1a6ef6fbcbdc880c929b/Screenshot%202024-07-05%20at%2013.19.41.png" alt="Screenshot 2024-07-05 at 13.19.41.png" />

**Comment by sadatmalik** [comment]
Pre and post flush_user_cache:

<img width="1444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemJqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fa032f5ecf6df58fa4e98156fa3ad48212b3638/Screenshot%202024-07-16%20at%2015.46.48.png" alt="Screenshot 2024-07-16 at 15.46.48.png" />

**Comment by sadatmalik** [comment]
Applied as a hot fix to prod - and tested to be working:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9262009043e8d4e727e8ad5dbdcfb1a34fac118/Screenshot%202024-07-16%20at%2016.19.57.png" alt="Screenshot 2024-07-16 at 16.19.57.png" />

Redis entries after flushing users cache:

<img width="1420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0RqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6707972c6d4b22974a132ad23389d0b51b9deaa0/Screenshot%202024-07-16%20at%2016.21.32.png" alt="Screenshot 2024-07-16 at 16.21.32.png" />

**Comment by sadatmalik** [comment]
Documented step by step instructions for usage here:
https://app.tettra.co/teams/talentbeyondboundaries/pages/recurring-tc-processes#header-76mk0-flushing-the-tc-redis-cache
