### ISSUE TITLE
UI updates from call with Naji

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#1253]
- [x] When copying list item to another list the modal is small and cuts off the end of the list dropdown. Make modal larger and use a hover over. (#1322 )
- [x] Add Intake latest to default columns, remove updated date from default - and add updated to some other screens (#1327)
- [x] Add 'Additional Information' section to general tab on candidate search card (#1327)

**Comment by cazcam34** [comment]
First check point - updated UI for select list modal component, made larger to fit list name and also fixed up CSS

Before:
<img width="972" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e45ce85daaa6e0293a55fd2541783e3739541d1/Screenshot%202024-08-26%20at%203.56.37%E2%80%AFPM.png" alt="Screenshot 2024-08-26 at 3.56.37 PM.png" />

<img width="775" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50b502134db75c73f1bce83673a27f8fa43f5909/Screenshot%202024-08-26%20at%203.57.38%E2%80%AFPM.png" alt="Screenshot 2024-08-26 at 3.57.38 PM.png" />


After:
<img width="1403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE9HQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7bbfdeef7ba0a7b4859f431351ebd249c859c6b/Screenshot%202024-08-26%20at%203.46.53%E2%80%AFPM.png" alt="Screenshot 2024-08-26 at 3.46.53 PM.png" />

<img width="1241" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFdHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae7475b6ae19c65c05ef0c5befa154c5d00b603a/Screenshot%202024-08-26%20at%203.46.58%E2%80%AFPM.png" alt="Screenshot 2024-08-26 at 3.46.58 PM.png" />
