### ISSUE TITLE
Release 2.3.0 planning

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1441]
As the tech team
we need to capture somewhere special manual tasks that have to be carried out for a release
so that we don't forget

Typically we will carry out these tasks progressively over time on staging, but all at once in production.

We should add the tasks as a task list as we carry them out on staging, then when we release into production, we just copy the task list, and mark them off as we complete them on production.

This type of issue starts in Review/QA so that we can always easily find it. It is only moved to Done when the production release is completed.

- Follow the [release runbook](https://github.com/Talent-Catalog/talentcatalog/wiki/Release#release-runbook)

# Staging task list
##  Pre-release:

- [x]  #1730 Add Duolingo API new environment variable to staging and production (Ehsan)

-  name: DUOLINGO_API_APISECRET,
-  value: fv7duvm328pkqz48

- [x] Create Terraform S3 bucket named tc-api-terraform-state for staging and prod
- [x] Confirm local AWS Terraform credentials
- [x] Create Mongo Atlas cluster for staging and prod
- [x]  Create Mongo database (tcapi) and collection (candidates) on staging and prod clusters
- [x] Update the Spring service config to connect to the Mongo Atlas URI (using Terraform) - staging and prod
- [x] Create tc-api TC user - staging and prod
- [x] Create tc-api search (include active, incomplete, pending, unreachable, employed)
- [x] Terraform the API service environment terraform init ;  terraform plan -out tfplan ; terraform apply "tfplan"

## Post-release:

- [x] Run Settings|AdminAPI set_public_ids - NOTE: Only needs to be run to completion once. It runs in the background and should not affect performance (configured to only use 20% of resources). It can take a couple of days to complete - but can be restarted. It does not change public_ids for entities that already have them.
- [x] Change the Duolingo Task description on production.  
- [x]  #1742 Run update SQL to populate the relocated_country_id with past relocated opps country id AND create candidate note
- [x] Run SystemAdminApi to add publicIds to all partners - set_public_ids
- [x] In Mongo Atlas -- Safe list the IP address from which the Spring service will be connecting (i.e. the NAT gateways public primary IP address - it will be visible from the VPC dashaboard sidebar)
- [x] Establish routing to api.tctalent.org (See: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer.html) Record type: A ; Alias: true ; Alias to Application and Classic Load Balacner ; Region: us-east-1 ; Choose load balancer: tc-api
- [x] Update task definition with password for aurora, mongo and TC
- [x] Initiate an entity and document anonymisation

## New Translations
- [x] chat_info.heading.candidate_prospect : Prospective Candidate Chat
- [x] chat_info.heading.all_job_candidates : All Candidates Chat
- [x] chat_info.heading.job_creator_source_partner : Source Partner Chat
- [x] chat_info.heading.candidate_recruiting	: Recruiting Candidate Chat
- [x] chat_info.heading.job_creator_all_source_partners : All Source Partners Chat
- [x] chat.notification_preference: Request extra notifications
- [x] chat.notification_preference_help: Normally you only receive chat notifications about jobs that you are being considered for when you have passed a certain stage in the process. However you can ask to receive notifications about jobs from an early stage. You may not be right for those jobs and may get eliminated early. Often employers do not give us any reason why they drop candidates early on - even though we always ask for feedback. We can notify you of those early jobs that you miss out on but you should not contact us asking why you didn't get the job. We probably won't know why and we do not have the resources to handle those questions. So you can ask to receive early notifications but you must promise not to contact us with questions if you do not get the job.

### Instructions: Production task list

To be copied from staging task list above, then worked through during the production release.
Translation text can be copied from Staging.

# Production task list

## Post-release:

Copied from staging:
- [x] Change the Duolingo Task description on production.  
- [x] In Mongo Atlas -- Safe list the IP address from which the Spring service will be connecting (i.e. the NAT gateways public primary IP address - it will be visible from the VPC dashaboard sidebar)
- [x] Establish routing to api.tctalent.org (See: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer.html) Record type: A ; Alias: true ; Alias to Application and Classic Load Balacner ; Region: us-east-1 ; Choose load balancer: tc-api
- [x] Update task definition with password for aurora, mongo and TC
- [x] Initiate an entity and document anonymisation

Added directly:
- [x] #1735 Set application.yml flyway.repair = false
- [x] Run Settings|AdminAPI set_public_ids - NOTE: Only needs to be run to completion once. It runs in the background and should not affect performance (configured to only use 20% of resources). It can take a couple of days to complete - but can be restarted because it does not change public_ids for entities that already have them.
- [x] #1742 Run update SQL to populate the relocated_country_id with past relocated opps country id AND create candidate note 
- [x] @samschlicht to test that relocation fields are being properly replicated in SF prod (#1745)
- [x] @samschlicht to add 'Program suspended' Candidate Opp stage to SF prod (#1987)
- [x] @samschlicht to check that Job and Case sync scheduled methods working in TC prod

## Release (API):

- [x] Terraform the API service environment terraform init ; terraform plan -out tfplan ; terraform apply "tfplan"
- [x] Push the API image

**Comment by EhsanEhrari** [comment]
[Add duolingo api new environment variable to staging and production](https://app.zenhub.com/workspaces/tc-engineering-646c91f0c3176e1ce584ec28/issues/gh/talent-catalog/talentcatalog/1730)
