### ISSUE TITLE
Create SF jobs from TC

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#351]
TC staff create jobs directly on SF at the moment. This doesn't work for recruiter access, who will not have access to SF.

We still need SF jobs to be created but this should all be done from the TC.

**Comment by camerojo** [comment]
- [x] Create employer table and link to it from job opp
- [x] Auto load from SF missing employers linked to from job opp - need to autocreate from lists of opps
- [x] Add Employer entity - mirrored on SF by equivalent Account object
- [x] All Job opportunities will link to an associated Employer instance - mirroring the SF account associated with the job opp on SF. 
- [x] Add link to Employer to Employer Access Partners
- [x] Add ability for System Admin to add an employer partner  
- [x] Employer access partner will be preconfigured with its Employer entity instance
- [x] Create different New Job front end when user is a job creating employer partner
- [x] Replace account related job fields with access through employer entity. employerWebsite, employerHiredInternationally, employerDescription
- [x] Create TC_id on production SF 
- [x] Need to add TC_id to SF Job Opportunity record on creation. 
- [x] Write SystemAdminAPI which creates Employer records for all existing job opps
- [x] Fix wording in Create job display
 
Moved to new issues
- [x] Saved lists and searches all accept SF links - need to change to accept jobs - see #550 
- [x] Rename external Salesforce IDs TBBid and TBBCandidateExternalId to TC equivalent names - see #552
- [x] Job names need to be unique - See #553

**Comment by camerojo** [comment]
This issue also completed issue #542
