### ISSUE TITLE
Release v2.2.0 planning

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#429]
As the tech team
we need to capture somewhere special manual tasks that have to be carried out for a release
so that we don't forget

Typically we will carry out these tasks progressively over time on staging, but all at once in production.

We should add the tasks as a task list as we carry them out on staging, then when we release into production, we just copy the task list, and mark them off as we complete them on production.

This type of issue starts in Review/QA so that we can always easily find it. It is only moved to Done when the production release is completed.

- Follow the [release runbook](https://github.com/Talent-Catalog/talentcatalog/wiki/Release#release-runbook)

**Comment by samschlicht** [comment]
<img width="1641" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEVwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9cc7269f2152dee73509d8bbceddec8f20e97bf0/Screenshot%202023-12-04%20at%2010.21.43%E2%80%AFam.png" alt="Screenshot 2023-12-04 at 10.21.43 am.png" />

**Comment by camerojo** [comment]
# Staging task list

- [x] Before starting the service, rename database from tbbtalent to tctalent. See #176
- [x] Upgrade to Postgres v 14.7
- [x] Upgrade to Provisioned Storage - see #85
- [x] Add new closing stage - Relocated no job offer pathway. See #257
- [x] SystemAdminApi create_employer_for_all_jobs
- [x] **The new release should be deployed from task definition 25** (different revision number on staging); NB: per [this post](https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1705009272502879), Sadat has changed the concurrent DB connection allowance, deployed as revision 26, so we may actually want to make a no. 27 that includes both these changes

## Post-release:
- [ ] @samschlicht to clean up the general-purpose SF contact record to omit candidate-specific fields - this can be done the day after the release
- [ ] @samschlicht to complete implementation of WB survey automation (#579)
- [ ] We have released with DB connection pool size at 50 - if there are post release performance issues with the database reduce this to 25 (See Task definition 26)

## New Translations

- [x] CANDIDATE-OPPS.TABLE.CHATS = 'Chats'
- [x] CANDIDATE-OPPS.OPP.CHAT-RETURN = 'Return to list of chats'
- [x] CANDIDATE-OPPS.TABLE.OFFER = 'Job offer'
- [x] CANDIDATE-OPPS.TABLE.SOURCE-CHAT = 'Chat with local partner'
- [x] CANDIDATE-OPPS.TABLE.DESTINATION-CHAT = 'Chat with local partner and destination partner'
- [x] CANDIDATE-OPPS.TABLE.ALL-JOB-CANDIDATES-CHAT = 'Chat with relocation support partners and other successful candidates'
- [x] CANDIDATE-OPPS.OPP.CHAT-MARK-AS-READ - 'Mark as Read'
- [x]  CANDIDATE-OPPS.OPP.JOB-RETURN - "Return to list of jobs"
- [x] CANDIDATE-OPPS.TABLE.INTERVIEW-GUIDANCE - "Interview Guidance"
- [x] LOGIN.BUTTON.ALREADY - "Already registered?" / "مسجلة بالفعل؟"
- [x] CHAT.NO-POSTS - "Send a message below to begin chat."
- [x] CHAT.POST-HEADER - "Post"
- [x] CHAT.POST-SEND - "Send"
- [x] REGISTRATION.HEADER.ACCOUNT.EXPLANATION - "To register your profile please create an account. You can log in anytime to update your profile." / ".لتسجيل ملف التعريف الخاص بك يرجى إنشاء حساب. يمكنك تسجيل الدخول في أي وقت لتحديث ملفك الشخصي"
- [x] REGISTRATION.HEADER.TITLE.ACCOUNT - "Welcome to Talent Catalog!" / "!مرحبا بكم في كتالوج المواهب"
- [x] REGISTRATION.COMPLETE.PARA1 - "Thank you for completing your profile on the Talent Catalog! {{partner}} will only contact you if an employer expresses interest in your profile. You can update your profile with additional information at any time. We recommend you continuously update your profile with any new information relevant to your professional experience or qualifications, as well as update any changes in your contact information."
- [x] REGISTRATION.CONTACT.LABEL.CONTACTCONSENTREGISTRATION - "I consent to being contacted by {{partner}} regarding my registration and employment opportunities." / ".أوافق على أن يتم الاتصال بي من قبل {{partner}} بخصوص التسجيل وفرص العمل الخاصة بي"
- [x]  REGISTRATION.CONTACT.LABEL.CONTACTCONSENTPARTNERS - "I consent to receive occasional emails from Talent Catalog partners regarding employment and vocational training opportunities for refugees and other displaced people." / ".أوافق على تلقي رسائل بريد إلكتروني من حين لآخر من شركاء Talent Catalog بخصوص فرص العمل والتدريب المهني للاجئين وغيرهم من النازحين"
- [x] REGISTRATION.LANDING.PARA2 - "The information you share will be used to identify relevant international employment opportunities, and your skills profile may be shared with interested employers. {{partner}} will not share your identifying details with any other parties without your consent. {{partner}} does publicly share anonymized, aggregate data about all registrants in the Talent Catalog." 
- [x] registration.personal.label.externalid - "ID assigned to you by the organisation other than {{partner}} or UNHCR  who is currently helping you. Afghan parolees, please add your A-number provided to you by USCIS."
- [x] registration.personal.label.unhcrconsent - "Do you consent to UNHCR being notified that you have created a Talent Catalog profile? "
- [x] registration.personal.note.unhcrregistered - "You do not need to be registered with the UN to be eligible for the Talent Catalog."

[Talent Catalog = كتالوج المواهب"

### Check/update these translations
- [x] REGISTRATION.CONTACT.LABEL.USERNAME - "Email (username)"
- [x] REGISTRATION.CONTACT.LABEL.PASSWORD - "Create password"
- [x] REGISTRATION.CONTACT.LABEL.PASSWORDCONFIRMATION - "Confirm password"
- [x] LANDING.PARA3 - "Please read our Privacy Policy for more information about how your data will be collected, stored and used. By registering with the Talent Catalog you are giving {{partner}} consent to use your data in accordance with the Privacy Policy."
- [x] HOME.PENDING.EXPLANATION - 'Thank you for completing your profile on the Talent Catalog! {{partner}} will only contact you if an employer expresses interest in your profile. You can update your profile with additional information at any time. We recommend you continuously update your profile with any new information relevant to your professional experience or qualifications, as well as update any changes in your contact information.'
- [x] HOME.ACTIVE.EXPLANATION - 'Thank you for completing your profile on the Talent Catalog! {{partner}} will only contact you if an employer expresses interest in your profile. You can update your profile with additional information at any time. We recommend you continuously update your profile with any new information relevant to your professional experience or qualifications, as well as update any changes in your contact information.'

**Comment by camerojo** [comment]
### Production task list

To be copied from staging task list above, then worked through during the production release.
Translation text can be copied from Staging.

# Production task list

## Pre-release
- [x] Add new closing stage - Relocated no job offer pathway. See #257

## Release
- [x] Before starting the service, rename database from tbbtalent to tctalent. See #176
- [x] **The new release should be deployed from task definition 25** (different revision number on staging); NB: per [this post](https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1705009272502879), Sadat has changed the concurrent DB connection allowance, deployed as revision 26, so we may actually want to make a no. 27 that includes both these changes
- [x] Upgrade to Provisioned Storage - see #85
- [x] Upgrade to Postgres v 14.7


## Post-release:
- [x] SystemAdminApi load_job_opps_and_candidate_opps
- [x] SystemAdminApi create_employer_for_all_jobs
- [x] Performance test - new search - monitor in PG admin
- [x] Test no job offer candidate opportunity stage
- [ ] @samschlicht to clean up the general-purpose SF contact record to omit candidate-specific fields - this can be done the day after the release
- [x] @samschlicht to complete implementation of WB survey automation (#579)
- [x] We have released with DB connection pool size at 50 - if there are post release performance issues with the database reduce this to 25 (See Task definition 26)

## New Translations

- [x] CANDIDATE-OPPS.TABLE.CHATS = 'Chats'
- [x] CANDIDATE-OPPS.OPP.CHAT-RETURN = 'Return to list of chats'
- [x] CANDIDATE-OPPS.TABLE.OFFER = 'Job offer'
- [x] CANDIDATE-OPPS.TABLE.SOURCE-CHAT = 'Chat with local partner'
- [x] CANDIDATE-OPPS.TABLE.DESTINATION-CHAT = 'Chat with local partner and destination partner'
- [x] CANDIDATE-OPPS.TABLE.ALL-JOB-CANDIDATES-CHAT = 'Chat with relocation support partners and other successful candidates'
- [x] CANDIDATE-OPPS.OPP.CHAT-MARK-AS-READ - 'Mark as Read'
- [x]  CANDIDATE-OPPS.OPP.JOB-RETURN - "Return to list of jobs"
- [x] CANDIDATE-OPPS.TABLE.INTERVIEW-GUIDANCE - "Interview Guidance"
- [x] LOGIN.BUTTON.ALREADY - "Already registered?" / "مسجلة بالفعل؟"
- [x] CHAT.NO-POSTS - "Send a message below to begin chat."
- [x] CHAT.POST-HEADER - "Post"
- [x] CHAT.POST-SEND - "Send"
- [x] REGISTRATION.HEADER.ACCOUNT.EXPLANATION - "To register your profile please create an account. You can log in anytime to update your profile." / ".لتسجيل ملف التعريف الخاص بك يرجى إنشاء حساب. يمكنك تسجيل الدخول في أي وقت لتحديث ملفك الشخصي"
- [x] REGISTRATION.HEADER.TITLE.ACCOUNT - "Welcome to Talent Catalog!" / "!مرحبا بكم في كتالوج المواهب"
- [x] REGISTRATION.COMPLETE.PARA1 - "Thank you for completing your profile on the Talent Catalog! {{partner}} will only contact you if an employer expresses interest in your profile. You can update your profile with additional information at any time. We recommend you continuously update your profile with any new information relevant to your professional experience or qualifications, as well as update any changes in your contact information."
- [x] REGISTRATION.CONTACT.LABEL.CONTACTCONSENTREGISTRATION - "I consent to being contacted by {{partner}} regarding my registration and employment opportunities." / ".أوافق على أن يتم الاتصال بي من قبل {{partner}} بخصوص التسجيل وفرص العمل الخاصة بي"
- [x]  REGISTRATION.CONTACT.LABEL.CONTACTCONSENTPARTNERS - "I consent to receive occasional emails from Talent Catalog partners regarding employment and vocational training opportunities for refugees and other displaced people." / ".أوافق على تلقي رسائل بريد إلكتروني من حين لآخر من شركاء Talent Catalog بخصوص فرص العمل والتدريب المهني للاجئين وغيرهم من النازحين"
- [x] REGISTRATION.LANDING.PARA2 - "The information you share will be used to identify relevant international employment opportunities, and your skills profile may be shared with interested employers. {{partner}} will not share your identifying details with any other parties without your consent. {{partner}} does publicly share anonymized, aggregate data about all registrants in the Talent Catalog." 
- [x] registration.personal.label.externalid - "ID assigned to you by the organisation other than {{partner}} or UNHCR  who is currently helping you. Afghan parolees, please add your A-number provided to you by USCIS."
- [x] registration.personal.label.unhcrconsent - "Do you consent to UNHCR being notified that you have created a Talent Catalog profile? "
- [x] registration.personal.note.unhcrregistered - "You do not need to be registered with the UN to be eligible for the Talent Catalog."

[Talent Catalog = كتالوج المواهب"

### Check/update these translations
- [x] REGISTRATION.CONTACT.LABEL.USERNAME - "Email (username)"
- [x] REGISTRATION.CONTACT.LABEL.PASSWORD - "Create password"
- [x] REGISTRATION.CONTACT.LABEL.PASSWORDCONFIRMATION - "Confirm password"
- [x] LANDING.PARA3 - "Please read our Privacy Policy for more information about how your data will be collected, stored and used. By registering with the Talent Catalog you are giving {{partner}} consent to use your data in accordance with the Privacy Policy."
- [x] HOME.PENDING.EXPLANATION - 'Thank you for completing your profile on the Talent Catalog! {{partner}} will only contact you if an employer expresses interest in your profile. You can update your profile with additional information at any time. We recommend you continuously update your profile with any new information relevant to your professional experience or qualifications, as well as update any changes in your contact information.'
- [x] HOME.ACTIVE.EXPLANATION - 'Thank you for completing your profile on the Talent Catalog! {{partner}} will only contact you if an employer expresses interest in your profile. You can update your profile with additional information at any time. We recommend you continuously update your profile with any new information relevant to your professional experience or qualifications, as well as update any changes in your contact information.'

**Comment by samschlicht** [comment]
Just a suggestion here: I had 3 release action items that were specific to prod and not relevant to staging. Understand the rationale to copy from staging but in future it'd be good to populate concurrently the Production task list. I've desisted from doing that this time to avoid any confusion.
