### ISSUE TITLE
Move to GA4 for candidate journey tracking

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#761]
All standard Universal Analytics properties will stop processing new hits on July 1, 2023, and 360 Universal Analytics properties will stop processing new hits on July 1, 2024. After that, you’ll be able to access your previously processed data in Universal Analytics for at least six months

https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/

**Comment by sadatmalik** [comment]
- [x] Add the GA4 tag (received from Comms team) to candidate portal index.html
- [x] (We should update the UA tag -> GA4 for admin portal too)
- [x] Ensure @types/google.analytics is installed
- [x] Call the gtag function to send a page view to Google Analytics to ensure that correct tracking of page views on route changes
- [x] Consider using environment variables for GA tracking ID.
- [x] Move all UA history to a data hub for year on year comparative history
