### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#821]
- [x] Confirm Ehcaching is working
- [x] Implement cache eviction
- [x] Id, email, phone number query related indexing
- [x] CandidateOpportuntyRepository opp/check-unread-chat - #865
- [x] Understand cpu profile discrepancy between AWS and Jprofiler
- [x] Open an AWS support ticket
- [x] Consider using AWS cloud profiler?
- [x] Investigate cpu spikes post start-up
- [x] Document JProfiler steps on TC Wiki - #894
- [x] Team JProfiler licenses - #894
- [x] Break out JobChats micro service? - future release

---

- Introduced a 30-minute max lifetime for prod DB connections in our Hikari config to alleviate stale DB connections as a Hotfix. This trumps the 24-hour timeout setting on the Postgres RDS DB.
- A PR for the same config is prepped and ready for staging.
- **Task 24 in Staging** is created for deployment once the above PR merges.

- Rebooted prod DB and despite seeing no stale connections, still have high CPU task usage & lingering sluggishness.
- Boosted AWS CPU to 1024 from 512, this has reduced sluggishness a little but still seeing high CPU spikes.
- Plan to dial back to 512 CPU once we unravel the mystery behind the high CPU usage. (edited)

**Comment by sadatmalik** [comment]
Next avenues to explore - CandidateOpportuntyRepository opp/check-unread-chats:

<img width="1206" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmsyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85f3ecb54fa4d53e10bf0c073b3d7db6f1b39b71/Screenshot%202024-04-04%20at%2018.04.49.png" alt="Screenshot 2024-04-04 at 18.04.49.png" />

**Comment by samschlicht** [comment]
Closed issue #794 is worth taking a look at again if we notice any connection between CPU spikes and file uploads.
