### ISSUE TITLE
Named look ups breaking on first and last name

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#942]
As a user
I want to be able to quick search on first name, last name, or full name
And for the search to be fast and responsive
So I can rapidly navigate to a candidate's profile.

---
Use elasticsearch for fast text searching on full name.

- [x] Elasticsearch index management scripts
  - [x] For initial index creation - with appropriate version number - and candidate alias
  - [x] For new index version number (with new mapping); reindexed from the old index; switching the alias
  - [x] Execute scripts on local cluster
  - [x] Execute scripts on staging cluster
  - [x] Execute scripts on production cluster - noted in release procedure

---
- [x] Back-end code complete:
  - [x] Confirm the use of index aliases with spring documents
  - [x] Implement elasticsearch service interface and implementation
    - [x] findByName
    - [x] findByNumber - opened as #985
    - [x] findByEmail - opened as #984
    - [x] findByPhone - opened as #984
    - [x] findByExternalId - opened as #984
    - [x] findByQueryStringAndSearchRequest (refactor from SavedSearchServiceImpl) - opened as #987
  - [x] Debug query logging only - noted as part of #984

---
- [x] Front-end code complete:
  - [x] Fix the name highlighting
